replit/replit-py

- .semaphore/semaphore.yml
- src/replit/database/__init__.py
This is useful for making sure that PRs pass the linter successfully. I also want to run tests for the Database client in the future.
The only thing Semaphore will do with this change is run flake8 against any files changed from master.
> use Semaphore for CI

- .semaphore/semaphore.yml
- poetry.lock
- pyproject.toml
- src/replit/database/__init__.py
- src/replit/test_database.py
Passing `encode=true` when listing keys causes all the returned key names to be URL encoded. This is good, since newlines don't break the delimiting. I've made the Database client do that.
I also sprinkled in some tests to make sure things are working as intended.
> use new key query param and add some tests

- .semaphore/semaphore.yml
Parts of Semaphore don't like that there was a space in the name. I renamed it so this isn't a problem anymore.
> change secret name

- src/replit/database/database.py
This prevents "unclosed socket" warnings. Need to update the tests to use this too.
> Add close method to synchronous DB client

- src/replit/web/utils.py
The name of the `authenticated` decorator was changed in #34. This PR adds an alias to the old name to help with backwards compatibility. 
This fixes the root cause of 1bd971a in #39.
> Add alias to utils

- .flake8
- src/replit/database/database.py
- tests/test_database.py
Add `ObserableList` and `ObservableDict` classes to the database module which enable nested setting of database keys. 
Closes #26.
> Add support for nested setting

- src/replit/database/database.py
- tests/test_database.py
Closes #42.
- Clarify docstring
- Implement get method
- Implement get_raw method
- Implement set_raw method
- Implement the set_bulk_raw method
- Implement set_bulk
- Implement async get_raw
- Implement async set_raw
- Implement async set_bulk and async set_bulk_raw
- Add set method to sync DB
- Add tests for raw operations
- Add tests for bulk setting
- Add tests for bulk raw setting
- flake8 fixes
- Fix mypy errors
> Add more database API methods

- src/replit/database/database.py
Subclass `collections.abc`s instead. This means that the classes cannot be JSON serialized directly, but users will have to live with that.
> Don't subclass builtins in database module

- src/replit/web/app.py
- Rename `request.user_info` to `request.auth`
- Add `is_authed` shorthand for `is_authenticated` for both ReplitRequest and ReplitUserContext
> Improve auth API

- src/replit/__main__.py
This allows non-seekable files, such as streams, to be used as the output file for the dump command.
> Use w instead of w+ when opening output file

- src/replit/__main__.py
The special DB values can not be dumped, causing a bug. This uses load(get_raw) so that is no longer an issue. Could also just use DBJSONEncoder in the dump cls kwarg, but this is easier and slightly more performant.
> Manually JSON decode DB values in CLI dump

- src/replit/web/user.py
The __iter__ method on a mapping should yield the keys of the mapping instead of values as it was doing before.
> Bug: Make UserStore iter yield keys

- src/replit/web/user.py
Reproduction: `UserStore().current.get("key_that_doesnt_exist_asefasef", []).append(1)` does not mutate the database when it should
We can't let MutableMapping implement this method because if it does it will return default directly instead of wrapping it in a special database method.
> Bugfix: Cannot mutate UserStore.get default

- src/replit/database/database.py
If a type truly isn't JSON-serializeable, then it will error out during JSON serialization. Fixes #73.
> Duck-type unknown types in item_to_observed

- .github/workflows/python-publish.yml
- Change trigger from release create to release publish
- Use poetry to build and publish instead of setup.py and twine
> Improve python-publish workflow

- src/replit/database/database.py
Before:
```py
ObservedDict(value={}).get("a", []) # => []
```
Now:
```py
ObservedDict(value={}).get("a", []) # => ObservedList(value=[])
```
> Observe default in ObservedDict get

- docs/web_tutorial.rst
from >>> return "You are not signed in! {web.sign_in_snippet}"
to >>> return f"You are not signed in! {web.sign_in_snippet}"
> f missing after return

- src/replit/database/database.py
In [replit/database/database.py, line 80](https://github.com/replit/replit-py/blob/master/src/replit/database/database.py#L80)
From:
```py
self.sess.close()
```
To:
```py
await self.sess.close()
```
Should fix #118
> Fix missing await statement in AsyncDatabase

- poetry.lock
- pyproject.toml
Having a Flask reference in both the dependencies and dev-dependencies is superfluous, so this commit just gets rid of it. :)
(Flask will still be installed, this does not affect the package at all.)
> Remove duplicate Flask dependency

- .semaphore/semaphore.yml
- docs/conf.py
- pyproject.toml
- src/replit/database/database.py
- src/replit/database/default_db.py
- tests/test_database.py
The JWT used for authenticating into the Replit DB is placed on the Repl as an environment variable on boot and lasts for 30h or so. This is fine for shorter lasting Repls, but if we want to have long-running Repls we need a mechanism to refresh the DB token.
Let's make it so that we read the DB URL data from a file, which can be refreshed while a program is running. If the file does not exist or we fail to read from it, fall back to the environment variable. We then run this hourly.
- Fork [this Repl](https://replit.com/@util/emoji-vote-kv)
- Change the version of the `replit` dependency in `pyproject.toml` to the latest commit in this branch. The resulting `[tool.poetry.dependencies]` section should look something like the following.
```
[tool.poetry.dependencies]
python = …
```
> Load Replit DB URL from a file

- .github/CODEOWNERS
- .github/pull_request_template.md
Why
===
* Show ownership
* Consistent PR messages
What changed
===
* Added DevEx as code owner
* Add standard PR template
Test plan
===
* See GitHub uses these as expected
> add CODEOWNERS and template

- tests/test_identity.py
Why
===
The token that was added 10m ago that was supposed to last 10y lasted less than one.
What changed
============
This change updates the token so that it lasts 100y and adds the little commandline snippet to regenerate it in case we need to.
Test plan
=========
```shell
~/replit-py$ poetry run python -m unittest tests/test_identity.py
Warning: error initializing database. Replit DB is not configured.
..
----------------------------------------------------------------------
Ran 2 tests in 0.030s
OK
```
Rollout
=======
> [👻] Update the Ghostwriter token

- src/replit/identity/__init__.py
- src/replit/identity/sign.py
- src/replit/identity/verify.py
- tests/test_identity.py
Why
===
We didn't implement signing tokens before. But it's time to allow that.
What changed
============
This change allows signing tokens and then verifying them.
Test plan
=========
```shell
PASSWORD=foo poetry run python -m unittest tests/test_identity.py 
```
Rollout
=======
> [identity] Allow signing tokens

- examples/web/authenticated.py
- examples/web/manual_auth.py
- examples/web/needs_params.py
- examples/web/ratelimit.py
- pyproject.toml
- src/replit/web/app.py
- src/replit/web/utils.py
next step should be to support Flask 3.0 by supporting Werkzeug 3.0. I have yet to test that
Why
===
prevent errors due to deprecated features (as seen in https://github.com/replit/replit-py/issues/188 in the part *after* Flask was downgraded as `poetry` wanted)
What changed
============
Support 2.3 by accounting for the deprecation of `json_encoder`
Test plan
=========
```bash
poetry update
```
Rollout
=======
> Support Flask 2.3

- pyproject.toml
Why
===
bump minor after supporting flask 2.3
What changed
============
version bump
> bump version to 3.4.0

- .github/workflows/release-drafter.yml
Why
===
We use [GitHub Releases](https://github.com/replit/replit-py/releases) to manage this repo. release-drafter improves the tending and creation of new releases, accumulating a list of PRs into a "Draft" release, which kicks off a proper release when promoted.
What changed
============
- Added standard release-drafter config
Test plan
=========
- Can't really test GHA before merge, due to the nature of them. This is basically the standard config taken directly from the README.
> Add release-drafter action

- .github/release-drafter.yml
- .github/workflows/python-publish.yml
- RELEASING
- RELEASING.md
- docs/conf.py
- pyproject.toml
Why
===
Removing footguns and making releases less cumbersome overall.
What changed
============
- Moving ownership of version-number-setting into GHA
- Bumping copyright
Test plan
=========
- Cutting the same version as was just released should kick the tires without breaking anything.
Rollout
=======
> Fully automatic release versioning

- .semaphore/semaphore.yml
- poetry.lock
- pyproject.toml
- src/replit/__main__.py
- src/replit/database/database.py
- tests/test_database.py
Why
===
CI is busted due to `aiohttp` socket being leaked between subsequent unittest runs
What changed
============
- Close the session
- Bump away from legacy Semaphore runner
- Add more file paths to semaphore file tracker so we actually run CI on version bump PRs.
Test plan
=========
- Ran unittest on python 3.8 and 3.11
Rollout
=======
> Close session to fix CI

- .flake8
- poetry.lock
- pyproject.toml
- src/replit/info.py
- src/replit/web/utils.py
- tests/test_database.py
Why
===
* Flask released a 3.0.0 version, which we couldn't support because of our version bounds. The changelog
https://flask.palletsprojects.com/en/3.0.x/changes/ looks innocuous for our purposes
What changed
===
* Changed pyproject.toml to use >=2.0.0 instead of ^2.0.0
* nix run nixpkgs#poetry -- lock --no-update
Test plan
===
* try installing this verison in a repl after it is released
* nix run nixpkgs#poetry -- check --lock
Rollout
=======
_Describe any procedures or requirements needed to roll this out safely (or check the box below)_
> chore: relax flask dependency constraint

- README.md
- pyproject.toml
Why
===
What changed
============
s/repl.it/Replit in pyproject.toml and README
Test plan
=========
Should see the description changes reflected after the next publish
> s/repl.it/Replit in pyproject.toml and README

- README.md
Why
===
This gif is painfully old. We should remove it since it doesn't reflect the product accurately anymore.
What changed
============
Remove outdated gif in README
Test plan
=========
- Open README
- No more outdated gif
> Remove outdated gif in README

- .replit
- README.md
- tests/test_identity.py
Why
===
Making it easier to develop replit-py on Replit
What changed
============
- `.replit`
- Patch tests to coexist with existing environ
Test plan
=========
`Run` should run tests inside a repl
Rollout
=======
> chore/Sensible defaults inside Replit

- main.sh
- src/replit/__init__.py
- src/replit/database/__init__.py
- src/replit/database/database.py
- src/replit/database/default_db.py
- src/replit/database/server.py
- src/replit/web/__init__.py
- src/replit/web/user.py
Why
===
Currently the replit library has a very gross quirk: it has a global in `replit.database.default_db.db`, and the mere action of importing this library causes side effects to run! (connects to the database, starts a thread to refresh the URL, and prints a warning to stdout, adding insult to injury).
What changed
============
So we're trading that very gross quirk with a gross workaround to preserve backwards compatibility: the modules that somehow end up importing that module now have a `__getattr__` that _lazily_ calls the code that used to be invoked as a side-effect of importing the library. Maybe in the future we'll deploy a breaking version of the library where we're not beholden to this backwards-compatibility quirck.
Test plan
=========
```shell
replit-py/src$ python3
Python …
```
> [replit] The lesser of two evils

- src/replit/database/database.py
- tests/test_database.py
If a key starts with a slash, then it becomes undeletable and prevents database purges from working properly as well. This prevents that from occuring by stripping slashes from the left of the key name.
Why
===
At least two separate occurrences where users have accidentally set a key that starts with a slash, and therefore can no longer remove the key or cleared their database.
What changed
============
Changed all references to `key` or `k` when setting a key-value pair to `keyStrip(key)` and `keyStrip(k)` respectively.
Test plan
=========
Attempted to set keys starting with slashes, then subsequently remove them and/or purge the database.
Rollout
=======
Prevents keys from being set with a slash in the future, which was is less breaking than the existing behavior (which is to not …
> [FIX] Prevent keys from starting with slashes

- README.md
Why
===
Swapping RTD section header to a shield. `passing` makes the CTA more dynamic, and having the logo and color should be eye catching.
What changed
============
Moved the RTD CTA to a shields.io shield
Test plan
=========
Rollout
=======
> Promoting RTD to a shield

- src/replit/database/database.py
Why
===
Especially with `default_db`, it's not clear that the user still needs to call `close()`. Monitor the main thread for termination to do this automatically.
What changed
============
The presumption is that users won't be relying on the database to hold the python runtime open, and that any instance of that is in fact some form of error.
Test plan
=========
```python
>>> from replit.database import db
>>> ^D
```
confirm that we exit cleanly and quickly.
Rollout
=======
No special instructions.
> Monitor main_thread in Database/AsyncDatabase to determine whether we need to automatically call close()

- poetry.lock
- pyproject.toml
Why
===
* Dependabot has a security warning that is resolved after starlette 0.40.0
What changed
===
* Add this indirect dependency to our pyproject.toml file and put the min version at the level where the security issue was resolved
Test plan
===
* CI passes
Rollout
=======
_Describe any procedures or requirements needed to roll this out safely (or check the box below)_
> [security] enforce min starlette version

- docs/requirements.in
- docs/requirements.txt
Why
===
* The zipp dependency used in the docs has a security report
* Let's fix it.
What changed
===
* Add zipp to requirements.in (bumping it from an indirect dependency to direct so we can control the version)
* run pip-compile
Test plan
===
* CI still builds the docs
Rollout
=======
_Describe any procedures or requirements needed to roll this out safely (or check the box below)_
> [docs][security] fix zipp security report
