src/replit/database/__init__.py
If this option is enabled, appropriate exceptions will be thrown whenever an error occurs and the user can handle them manually. 
This disables the built-in automatic default writing and `_should_discard_prompt` but gives users greater control over how errors are handled.
Closes #2
=> Add new raises kwarg to JSONKey

src/replit/termutils.py
Several things in it were not valid Python, ~there were some undefined references~, and it needed to be run through `black`.
=> fix termutils

.flake8, .semaphore/semaphore.yml, poetry.lock, pyproject.toml, src/replit/__init__.py, src/replit/audio/__init__.py, src/replit/audio/test.py, src/replit/audio/types.py, src/replit/database/__init__.py, src/replit/maqpy/__init__.py, src/replit/maqpy/app.py, src/replit/maqpy/html.py, src/replit/maqpy/utils.py
Adds new Async Database Client, new utilities, bug fixes from dev branch, and fixes linting errors in audio code.
=> Make audio lint without errors

src/replit/database/__init__.py, src/replit/web/utils.py
=> Quick lint fixes

src/replit/database/database.py
Adds a dumps method for convienience.
=> Add dumps method to DB

src/replit/web/app.py
Makes it so that if a route returns a special `ObservedList` or `ObservedDict` it will be serialized properly.
=> Add JSONEncoder for web app

src/replit/web/__init__.py, src/replit/web/user.py
Add `web.UserStore` and `web.User`
Passes mypy and flake8.
=> Add users feature

src/replit/database/__init__.py, src/replit/database/database.py
- Add a `sess` attribute for async database
- Export `to_primitive`, `dumps`, and `DBJSONEncoder` in database module
=> API Improvements

src/replit/__main__.py
Fixes an error while running the CLI.
=> Use click.option instead of cli.option in CLI

poetry.lock, pyproject.toml
=> Remove unnecessary dependency

src/replit/__init__.py, src/replit/database/__init__.py, src/replit/database/default_db.py, src/replit/database/server.py
- Implement a database proxy
- Move the default database into a separate file
=> Implement database proxy

docs/api.rst
=> Add missing modules to API reference

docs/cli.rst, docs/conf.py, docs/index.rst, poetry.lock, pyproject.toml
=> Setup sphinx documentation for CLI

docs/api.rst, src/replit/__init__.py, src/replit/info.py, src/replit/web/user.py, src/replit/web/utils.py
Implements variables about the current repl. Closes #18.
=> Implement replit.info

src/replit/web/utils.py
Got this request from discord. Closes #67.
=> Add authenticated_template utility

pyproject.toml
Installing the package did not install requests, I added requests to the dependencies.
=> Added requests to dependencies

src/replit/database/server.py
=> Minor spelling mistake

docs/db_tutorial.rst
This isn't Javascript :P
The example would have given a syntax error for improper ordering.
=> Fix incorrect import statement

pyproject.toml
What changed
============
- Bumping werkzeug
=> Bump version to 3.5.0

.github/release-drafter.yml
=> Add release-drafter config, in preparation for action
